Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2022-08, with the labels that each got.

#1386 devolucion fondo de retiro
  app/Http/Controllers/EconomicComplementController.php
  app/Http/Controllers/QuotaAidMortuaryController.php
  app/Http/Controllers/RetirementFundController.php
  app/Models/EconomicComplement/EconomicComplement.php
  app/Models/QuotaAidMortuary/QuotaAidMortuary.php
  app/Models/RetirementFund/RetirementFund.php
  app/Observers/EconomicComplementObserver.php
  app/Observers/QuotaAidMortuaryObserver.php
  app/Observers/RetirementFundObserver.php
  database/migrations/2022_07_26_155001_add_columns_wf_records_table.php
Labels: enhancement

#1389 obtencion de extencion de expedicion de ci
  app/Http/Controllers/RetirementFundController.php
  app/Models/Affiliate.php
  resources/assets/js/components/quota_aid/Beneficiary.vue
  resources/assets/js/components/ret_fun/Beneficiary.vue
  resources/views/affiliates/print/info.blade.php
  resources/views/quota_aid/step2_applicant.blade.php
  resources/views/ret_fun/info.blade.php
  resources/views/ret_fun/step2_applicant.blade.php
Labels: change

#1392 impresion de devolucion de trramites
  app/Http/Controllers/InboxController.php
  app/Models/RetirementFund/RetirementFund.php
  resources/assets/js/components/inbox/SendBackButtonQuotaAid.vue
  resources/assets/js/components/inbox/SendBackButtonRetFun.vue
  resources/views/print_global/backward.blade.php
Labels: enhancement

#1395 modificacion de calificacion de FRPS, PGA, DA nuevo reglamento
  app/Http/Controllers/RetirementFundCertificationController.php
  app/Http/Controllers/RetirementFundController.php
  app/Models/Affiliate.php
  database/seeds/ColumnsContributionTypesTableSeeder.php
  resources/views/ret_fun/print/interval_types.blade.php
  resources/views/ret_fun/print/qualification_beneficiaries_fair_share.blade.php
  resources/views/ret_fun/print/qualification_contribution_plus.blade.php
  resources/views/ret_fun/print/qualification_data_availability.blade.php
  resources/views/ret_fun/print/qualification_data_ret_fun_availability.blade.php
  resources/views/ret_fun/print/qualification_step_data.blade.php
  resources/views/ret_fun/qualification.blade.php
  resources/views/ret_fun/summary_qualification.blade.php
Labels: change

#1402 Resoluciones de las modalidades para Pago del Beneficio de Fondo de Retiro Policial Solidario, Devolución de Aportes y Pago Global de Aportes
  app/Http/Controllers/RetirementFundCertificationController.php
  app/Models/RetirementFund/RetFunBeneficiary.php
  app/Models/RetirementFund/RetFunLegalGuardian.php
  resources/views/ret_fun/print/legal_resolution.blade.php
Labels: php

#1404 cambio de redacción beneficiario Menor para la devolución de aportes en disponibilidad y en el total pago
  app/Http/Controllers/RetirementFundCertificationController.php
Labels: change

#1405 modificacion de seeder de documentos y adicion de softdelete a contri…
  app/Models/Contribution/ContributionType.php
  app/Models/Contribution/ContributionTypeQuotaAid.php
  database/seeds/ProcedureDevPaySeeder.php
  resources/views/ret_fun/print/beneficiaries_qualification.blade.php
  resources/views/ret_fun/show.blade.php
Labels: change
