Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2022-10, with the labels that each got.

#1509 solución a bugs authcontrollers
  app/Http/Controllers/API/AuthController.php
Labels: bug

#1510 comentando campo requerido firebase token
  app/Http/Requests/API/AuthForm.php
Labels: change

#1512 eliminando migración duplicada de la tabla affiliate_tokens
  database/migrations/2022_09_07_151958_create_affiliate_tokens_table.php
Labels: change

#1518 Cambios en el login aplicación
  app/Http/Controllers/API/AuthController.php
  app/Http/Controllers/AffiliateController.php
  app/Http/Controllers/EconomicComplementController.php
  app/Models/AffiliateToken.php
  resources/assets/js/app.js
  resources/assets/js/components/affiliate/Photo.vue
  resources/views/affiliates/photos.blade.php
  resources/views/affiliates/show.blade.php
  resources/views/eco_com/boleta.blade.php
  resources/views/eco_com/show.blade.php
Labels: change

#1522 Agregar columnas de (contraste de CI y notificación) en reporte de complemento todos los tramites
  app/Exports/EcoComReports.php
  app/Models/EconomicComplement/EconomicComplement.php
Labels: enhancement

#1528 Adicion de columna de date_last_cointribution y modificacion para cue…
  app/Helpers/Util.php
  app/Http/Controllers/AffiliateController.php
  app/Http/Controllers/AidCommitmentController.php
  app/Http/Controllers/AidContributionController.php
  app/Http/Controllers/ContributionController.php
  app/Http/Controllers/DirectContributionController.php
  app/Http/Controllers/QuotaAidMortuaryController.php
  app/Http/Controllers/RetirementFundController.php
  app/Models/Affiliate.php
  database/migrations/2022_10_05_161005_add_column_last_period_date_affiliates.php
  resources/assets/js/app.js
  resources/views/affiliates/affiliate_police_information.blade.php
  resources/views/contribution/print/certification_aid_contribution.blade.php
  resources/views/contribution/select.blade.php
Labels: change

#1533 Adicion de informacion form calificacion en complemento
  resources/views/eco_com/print/qualification.blade.php
  resources/views/eco_com/print/ticket.blade.php
Labels: change
