Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2022-07, with the labels that each got.

#1360 adicion de reporte de historial de la vida policial del afiliado segu…
  app/Http/Controllers/AffiliateReportController.php
  resources/views/affiliates/affiliate_record.blade.php
  resources/views/ret_fun/print/print_record_affiliate.blade.php
  routes/web.php
Labels: enhancement

#1363 modificacion de listado de requisitos utilizando el deleted at
  app/Http/Controllers/RetirementFundController.php
  database/seeds/ProcedureDevPaySeeder.php
Labels: change

#1375 actualizacion de afiliados en pago global de aportes
  app/Http/Controllers/RetirementFundController.php
Labels: bug
