Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2022-09, with the labels that each got.

#1410 Modificación de calculos para Pago global de aportes solo fondo de re…
  app/Http/Controllers/RetirementFundController.php
  resources/views/quota_aid/qualification.blade.php
  resources/views/ret_fun/qualification.blade.php
Labels: change

#1393 adicion de descarga de lote diario para envio a banco
  app/Exports/EcoComBankExport.php
  app/Exports/EcoComBankExportHeaderSheet.php
  app/Exports/EcoComBankExportSheet.php
  app/Helpers/Util.php
  resources/assets/js/components/eco_com/SelectReport.vue
Labels: change

#1431 adicion de visualización de qr en fondo y quota en recepcion
  app/Http/Controllers/QuotaAidCertificationController.php
  app/Http/Controllers/RetirementFundCertificationController.php
  resources/views/quota_aid/print/footer_qr.blade.php
  resources/views/ret_fun/print/footer_qr.blade.php
Labels: change

#1432 adicion de validadcion para que se califique deacuerdo a la modalidadad
  app/Http/Controllers/RetirementFundController.php
Labels: change

#1454 Login app
  app/Http/Controllers/AffiliateController.php
  app/Imports/EcoComImportPagoFuturo.php
  resources/assets/js/components/affiliate/ShowAffiliate.vue
  resources/views/affiliates/affiliate_personal_information.blade.php
  routes/web.php
Labels: change

#1485 solución firebase token duplicado
  app/Http/Controllers/API/AuthController.php
  app/Http/Controllers/API/LivenessController.php
  database/migrations/2022_09_07_151958_create_affiliate_tokens_table.php
Labels: bug

#1486 Creación de opción para ver fotos del afiliado vejez y viudedad en la interfaz del afiliado
  app/Http/Controllers/AffiliateController.php
  resources/views/affiliates/deceased.blade.php
  resources/views/affiliates/show.blade.php
Labels: enhancement
