Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2023-04, with the labels that each got.

#1625 arreglando bug de visualización de observaciones en el historial del …
  resources/assets/js/components/affiliate/Record.vue
Labels: hotfix

#1629 correcion de bug e la creacion de aportes
  app/Http/Controllers/AidContributionController.php
  app/Models/Contribution/AidContribution.php
  resources/views/contribution/affiliate_aid_contributions_edit.blade.php
Labels: bug

#1653 modificacion de modalidades
  app/Http/Controllers/QuotaAidCertificationController.php
  database/migrations/2023_02_10_132612_alter_columns_quota.php
Labels: change
