Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2023-06, with the labels that each got.

#1699 Development
  app/Models/Affiliate.php
Labels: bug

#1698 Adicionando versión de la aplicación móvil para la aplicación móvil
  app/Http/Controllers/API/VersionController.php
Labels: hotfix

#1705 Corrección inconsistencia en resoluciones
  app/Http/Controllers/QuotaAidCertificationController.php
Labels: bug

#1716 Modificación de requisitos de Fondo, Cuota y Auxilio Mortuorio
  app/Helpers/Util.php
  app/Http/Controllers/QuotaAidCertificationController.php
  app/Models/Kinship.php
  app/Models/ProcedureDocument.php
  database/migrations/2023_06_27_093801_add_column_deleted_at_procedure_documents_table.php
  database/seeds/AddAditionalDocumentSeeder.php
  database/seeds/AddKinshipSeeder.php
  database/seeds/AditionalDocumentRequirementsSeeder.php
  database/seeds/DeleteRegisterProcedureDocuments.php
  database/seeds/UpdateTextRegisterSeeder.php
  resources/views/print_global/applicant_info.blade.php
  resources/views/quota_aid/print/reception.blade.php
  resources/views/ret_fun/print/reception.blade.php
Labels: enhancement, change
