Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2023-08, with the labels that each got.

#1737 Agregando documentos adicionales y eliminando documentos requeridos en todas las modalidades de Fondo de Retiro
  .gitignore
  database/seeds/AditionalDocumentRequirementsSeeder.php
  database/seeds/ChangeOfNameSubmodalitiesQuotaAidSeeder.php
  database/seeds/DeleteRegisterProcedureRequirementsSeeder.php
  resources/views/quota_aid/print/reception.blade.php
  resources/views/ret_fun/print/reception.blade.php
Labels: enhancement

#1738 Modificaciones de forma en los nombres de las submodalidades de Cuota…
  database/seeds/ChangeOfNameSubmodalitiesQuotaAidSeeder.php
  database/seeds/UpdateTextRegisterSeeder.php
Labels: enhancement

#1739 Agregando documentos adicionales a las submodalidades Retiro Forzoso …
  database/seeds/AditionalDocumentRequirementsSeeder.php
Labels: enhancement

#1740 Cambios en los documentos requeridos en Fondo de Retiro
  database/seeds/AditionalDocumentRequirementsSeeder.php
  database/seeds/DeleteRegisterProcedureRequirementsSeeder.php
  database/seeds/UpdateTextRegisterSeeder.php
Labels: enhancement

#1746 Arreglando la impresión de Certificación de documentos presentados de…
  app/Models/RetirementFund/RetFunSubmittedDocument.php
Labels: bug

#1749 ciudad de expedicion reportes de complemento
  app/Exports/AffiliateSpouseReport.php
  app/Exports/AffiliateTagSheet.php
  app/Exports/AffiliateTagsReport.php
  app/Exports/EcoComObservationReport.php
  app/Exports/EcoComObservationSheet.php
  app/Exports/EcoComReports.php
  app/Exports/EcoComStateReport.php
  app/Exports/EcoComStateSheet.php
  app/Exports/EcoComTagSheet.php
  app/Exports/EcoComTagsReport.php
  app/Exports/PlanillaGeneral/EcoComMoreObservationNoAmortizableSheet.php
  app/Exports/PlanillaGeneral/EcoComMoreObservationSheet.php
  app/Exports/PlanillaGeneral/EcoComOneObservationSheet.php
  app/Exports/PlanillaGeneral/EcoComOneStateSheet.php
  app/Http/Controllers/EconomicComplementController.php
  app/Models/Affiliate.php
  app/Models/EconomicComplement/EconomicComplement.php
Labels: change
