Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2023-10, with the labels that each got.

#1759 Cambio de texto en el footer del Formulario de Solicitud de Pago de CE
  resources/views/eco_com/print/footer.blade.php
Labels: change

#1760 Modificando versiones de la aplicación móvil
  app/Http/Controllers/API/VersionController.php
Labels: enhancement

#1763 adición del campo Validado_por en el reporte Todos_los_trámites CE
  app/Exports/EcoComReports.php
  app/Http/Controllers/ReimbursementController.php
  app/Models/EconomicComplement/EconomicComplement.php
  app/Observers/ContributionObserver.php
  app/Observers/ReimbursementObserver.php
  app/Providers/AppServiceProvider.php
  resources/views/contribution/affiliate_contributions_edit.blade.php
Labels: enhancement, change

#1765 Modificación de glosa del Formulario de Recepción Cuota y Auxilio Mo…
  resources/views/quota_aid/print/reception.blade.php
Labels: change

#1767 Modificación de las resoluciones de legal Cuota y Auxilio mortuorio
  app/Http/Controllers/QuotaAidCertificationController.php
  app/Models/QuotaAidMortuary/QuotaAidSubmittedDocument.php
  resources/views/quota_aid/print/legal_certification.blade.php
Labels: change

#1770 migraciones de BD para pago por unica vez
  database/migrations/2023_10_19_104508_create_eco_com_once_payment.php
  database/migrations/2023_10_20_115308_alter_column_is_paid_spouse.php
Labels: enhancement

#1771 cambio a pago por unica vez e implementacion de modelos
  app/Exports/EcoComReports.php
  app/Models/EconomicComplement/EcoComOncePayment.php
  app/Models/EconomicComplement/EconomicComplement.php
  app/Observers/EconomicComplementObserver.php
  resources/assets/js/components/eco_com/Info.vue
Labels: enhancement

#1773 Modificaciones de forma en resoluciones según ticket
  app/Http/Controllers/QuotaAidCertificationController.php
Labels: change

#1772 Migraciones, modelos y seeder review_procedures, eco_com_review_proce…
  app/Http/Controllers/EcoComReviewProcedureController.php
  app/Http/Controllers/EconomicComplementController.php
  app/Http/Controllers/ReviewProcedureController.php
  app/Models/EconomicComplement/EcoComReviewProcedure.php
  app/Models/EconomicComplement/EconomicComplement.php
  app/Models/EconomicComplement/ReviewProcedure.php
  app/User.php
  database/migrations/2023_10_12_102428_create_review_procedures_table.php
  database/migrations/2023_10_12_104216_create_eco_com_review_procedures_table.php
  database/seeds/ReviewProceduresTableSeeder.php
  routes/web.php
Labels: change, data base, New

#1774 método de edición y reporte del certificado de revisión eco_com
  app/Http/Controllers/EcoComCertificationController.php
  app/Http/Controllers/EconomicComplementController.php
  resources/views/eco_com/print/revision_certificate.blade.php
  routes/web.php
Labels: change
