Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2023-11, with the labels that each got.

#1778 validacion del nua en la creacion del tramite
  app/Http/Controllers/EconomicComplementController.php
  resources/assets/js/components/eco_com/Info.vue
Labels: enhancement

#1781 Observer para la revisión del trámite
  app/Http/Controllers/EcoComCertificationController.php
  app/Http/Controllers/EconomicComplementController.php
  app/Observers/EconomicComplementObserver.php
  resources/views/eco_com/print/revision_certificate.blade.php
Labels: bug, change

#1784 Observer para la revisión del trámite, correción de bugs
  app/Http/Controllers/EconomicComplementController.php
  app/Observers/EconomicComplementObserver.php
Labels: bug

#1792 Modificación de texto en el Certificado de revisión
  app/Http/Controllers/EcoComCertificationController.php
  resources/views/eco_com/print/revision_certificate.blade.php
Labels: change

#1790 Modificaciones de forma a resoluciones QAM
  app/Http/Controllers/QuotaAidCertificationController.php
Labels: change

#1800 Arreglando texto en las resoluciones
  app/Http/Controllers/QuotaAidCertificationController.php
Labels: change

#1802 Adicionando distinción por modalidad Quota y Auxilio mortuorio
  app/Http/Controllers/QuotaAidCertificationController.php
Labels: change
