Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2024-08, with the labels that each got.

#1927 Agregando tiempo de espera en la creación de trámites de Fondo de Ret…
  resources/assets/js/components/quota_aid/Form.vue
  resources/assets/js/components/ret_fun/Form.vue
  resources/views/quota_aid/create.blade.php
  resources/views/ret_fun/create.blade.php
Labels: enhancement

#1928 Quitando botón de cambio de amortización
  resources/assets/js/components/eco_com/Amortization.vue
Labels: change

#1930 Implementación de retenciones, adicionando interfaz en área legal de QAM para registrar retenciones
  app/Http/Controllers/QuotaAidCertificationController.php
  app/Http/Controllers/QuotaAidMortuaryController.php
  resources/assets/js/app.js
  resources/assets/js/components/quota_aid/JudicialRetention.vue
  resources/views/quota_aid/beneficiaries_list.blade.php
  routes/web.php
Labels: enhancement

#1931 Agregando descuento por retención de juzgado al área de calificación …
  app/Http/Controllers/QuotaAidMortuaryController.php
  resources/assets/js/components/quota_aid/Qualification.vue
  resources/views/quota_aid/beneficiaries_list.blade.php
  resources/views/quota_aid/qualification.blade.php
  routes/web.php
Labels: enhancement

#1932 Añadir liquidación al flujo de cuota y auxilio
  app/Http/Controllers/QuotaAidCertificationController.php
  resources/views/quota_aid/print/liquidation.blade.php
  resources/views/quota_aid/show.blade.php
  routes/web.php
Labels: New

#1933 Arreglando error en el registro de anticipos para QAM
  app/Http/Controllers/QuotaAidMortuaryController.php
  resources/views/quota_aid/print/reception.blade.php
  resources/views/ret_fun/print/reception.blade.php
Labels: bug, enhancement

#1934 Migración para añadir el rol de liquidación para cuota y auxilio
  database/migrations/2024_08_13_155935_add_liquidation_role.php
Labels: data base, New

#1935 Arreglos en formularios
  app/Http/Controllers/QuotaAidCertificationController.php
  resources/views/quota_aid/print/liquidation.blade.php
  resources/views/quota_aid/print/qualification_data.blade.php
Labels: bug

#1937 Corrigiendo bugs y agregando tabla para mostrar las retenciones en ár…
  app/Http/Controllers/ContributionController.php
  app/Http/Controllers/QuotaAidMortuaryController.php
  resources/assets/js/components/quota_aid/JudicialRetention.vue
  resources/views/quota_aid/beneficiaries_list.blade.php
Labels: bug, enhancement

#1938 Agregando nuevo tipo de descuento
  app/Http/Controllers/QuotaAidMortuaryController.php
  database/seeds/AddDiscountTypeSeeder.php
Labels: change

#1939 Cambio de id en modalidad
  app/Http/Controllers/QuotaAidCertificationController.php
  resources/views/quota_aid/print/liquidation.blade.php
  resources/views/quota_aid/print/qualification_data.blade.php
Labels: bug

#1940 Agregando edición y anulación de las retenciones en el área Legal de QAM
  app/Http/Controllers/QuotaAidMortuaryController.php
  app/Models/QuotaAidMortuary/QuotaAidMortuary.php
  database/migrations/2024_08_14_173245_added_column_deleted_at_discount_types_quota_aid.php
  database/seeds/AddDiscountTypeSeeder.php
  resources/assets/js/components/quota_aid/JudicialRetention.vue
  resources/assets/js/components/quota_aid/Step1RequirementsEdit.vue
  routes/web.php
Labels: change

#1942 Creación de botón para imprimir la boleta de pago en el listado de complemento económico
  app/Http/Controllers/EconomicComplementController.php
  resources/views/eco_com/index.blade.php
Labels: enhancement

#1949 Modificaciones según ticket aperturado
  app/Http/Controllers/QuotaAidCertificationController.php
  resources/assets/js/components/quota_aid/Qualification.vue
  resources/views/quota_aid/print/qualification_data.blade.php
Labels: change

#1948 Nueva modalidad - Fallecimiento Cónyuge Cuota Mortuoria
  app/Helpers/Util.php
  app/Http/Controllers/ContributionController.php
  app/Http/Controllers/QuotaAidCertificationController.php
  app/Http/Controllers/QuotaAidMortuaryController.php
  app/Models/Affiliate.php
  app/Models/QuotaAidMortuary/QuotaAidMortuary.php
  database/seeds/AddSpouseDeceasedQuotaMortuaryModalitySeeder.php
  resources/views/contribution/print/certification_quota_contribution.blade.php
  resources/views/quota_aid/print/liquidation.blade.php
  resources/views/quota_aid/show.blade.php
Labels: New

#1956 Cambios en la validación de campos en creación de trámite
  app/Http/Controllers/QuotaAidMortuaryController.php
  resources/assets/js/components/quota_aid/Form.vue
  resources/assets/js/components/quota_aid/Step1Requirements.vue
  resources/assets/js/components/quota_aid/Step2Applicant.vue
  resources/assets/js/store/modules/quotaAid/form.js
Labels: bug
