Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2024-07, with the labels that each got.

#1909 Se añadio la columna Type_rent a Todos los Trámites
  app/Exports/EcoComReports.php
Labels: change

#1914 Quitando amortización "Retención según Juzgado"
  resources/assets/js/components/eco_com/Amortization.vue
Labels: change

#1905 Agregando validación para verificar si tiene compromiso de pago, en l…
  app/Http/Controllers/AffiliateDevolutionController.php
  resources/assets/js/components/affiliate/Devolutions.vue
Labels: bug, enhancement

#1923 Modificación del formulario de recepción, para la visualización del n…
  resources/views/print_global/applicant_info.blade.php
  resources/views/ret_fun/print/reception.blade.php
Labels: enhancement
