Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2024-09, with the labels that each got.

#1958 Agregando los bonos: estudio, cargo, frontera y oriente, en la secció…
  app/Http/Controllers/ContributionController.php
  app/Observers/ContributionObserver.php
  resources/views/contribution/affiliate_contributions_edit.blade.php
Labels: enhancement

#1961 Refactorización de edición de aportes
  app/Http/Controllers/ContributionController.php
Labels: test

#1963 Habilitando la edición de los campos sueldo base y antiguedad en el listado de aportes
  resources/views/contribution/affiliate_contributions_edit.blade.php
Labels: change

#1965 Validación de NAN en actualización de bonos
  app/Http/Controllers/ContributionController.php
Labels: New

#1967 Seeder para actualizar requerimientos de cuota y auxilio
  database/seeds/UpdateRequirementsQuotaAidSeeder.php
Labels: change, data base
