Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2024-05, with the labels that each got.

#1854 Acceso al personal de las regionales y recepción La Paz a modificar campos, si están en su bandeja
  app/Exports/EcoComReports.php
  app/Http/Controllers/EconomicComplementController.php
  app/Models/EconomicComplement/EconomicComplement.php
  app/Observers/EconomicComplementObserver.php
  resources/assets/js/components/affiliate/Police.vue
  resources/assets/js/components/eco_com/Info.vue
  resources/assets/js/components/eco_com/Step1Requirements.vue
  resources/assets/js/components/eco_com/Step2Beneficiary.vue
  resources/views/affiliates/affiliate_police_information.blade.php
  resources/views/eco_com/show.blade.php
Labels: enhancement

#1851 Nuevas migraciones para el cálculo de CE
  database/migrations/2024_04_24_181041_create_regulations_table.php
  database/migrations/2024_04_25_094042_create_fixed_pensions_table.php
  database/migrations/2024_04_25_094120_create_updated_pensions_table.php
  database/migrations/2024_04_29_151210_add_regulation_id_to_eco_com_procedures_table.php
  database/migrations/2024_04_29_153828_add_fixed_pension_id_to_economic_complements_table.php
Labels: New

#1857 Se añadieron modelos y se corrigió una migración
  app/Http/Controllers/EcoComFixedPensionController.php
  app/Http/Controllers/EcoComRegulationController.php
  app/Http/Controllers/EcoComUpdatedPensionController.php
  app/Models/Affiliate.php
  app/Models/EconomicComplement/EcoComFixedPension.php
  app/Models/EconomicComplement/EcoComProcedure.php
  app/Models/EconomicComplement/EcoComRegulation.php
  app/Models/EconomicComplement/EcoComUpdatedPension.php
  app/Models/EconomicComplement/EconomicComplement.php
  app/User.php
  database/migrations/2024_04_29_151210_add_regulation_id_to_eco_com_procedures_table.php
Labels: New

#1860 Acceso a las regionales y área de recepción para edición de campos
  app/Http/Controllers/EconomicComplementController.php
  resources/assets/js/components/affiliate/Police.vue
  resources/assets/js/components/eco_com/Info.vue
  resources/assets/js/components/eco_com/Step2Beneficiary.vue
  resources/views/affiliates/affiliate_police_information.blade.php
  resources/views/affiliates/show.blade.php
  resources/views/eco_com/show.blade.php
Labels: enhancement, change

#1859 Cambio de destino de la importación de pensiones a updatedPensions
  app/Http/Controllers/EcoComImportExportController.php
  app/Models/EconomicComplement/EcoComUpdatedPension.php
Labels: change

#1862 Cambios en la función importPagoFuturo
  app/Http/Controllers/EcoComImportExportController.php
  app/Http/Controllers/EconomicComplementController.php
  app/Models/EconomicComplement/EcoComFixedPension.php
  resources/assets/js/components/eco_com/Qualification.vue
Labels: change

#1863 Calificacion
  app/Http/Controllers/EcoComImportExportController.php
  app/Http/Controllers/EconomicComplementController.php
  app/Models/EconomicComplement/EcoComFixedPension.php
  resources/assets/js/components/eco_com/Qualification.vue
Labels: change

#1868 Implementación de los estados 'Exclusion por semestre' y 'Exclusion d…
  app/Http/Controllers/EconomicComplementController.php
  app/Http/Controllers/SearcherController.php
  app/Models/EconomicComplement/EcoComState.php
  database/seeds/AddStateEcoComState.php
  database/seeds/UpdateObservationTypeSeeder.php
  resources/assets/js/components/eco_com/Info.vue
Labels: change

#1869 Agregando registro de descuento por juzgado
  resources/assets/js/components/eco_com/Amortization.vue
Labels: enhancement, change

#1870 Retención según juzgado
  app/Http/Controllers/EconomicComplementController.php
  database/seeds/DiscountTypeSeeder.php
Labels: enhancement

#1873 Correccion de bug para el registro de los campos, grado, categoria, e…
  resources/assets/js/components/eco_com/Step1Requirements.vue
  resources/assets/js/components/eco_com/Step2Beneficiary.vue
Labels: bug

#1875 Creación de estado no pagado - retenido en eco_com_states
  database/seeds/AddStateEcoComState.php
Labels: enhancement

#1877 Modificaciones de nombre de las exclusiones semestrales y definitivas
  database/seeds/UpdateObservationTypeSeeder.php
Labels: change

#1878 Adición de las columna retención según juzgado a reportes de planillas de pago
  app/Exports/EcoComPlanillaGeneralPagos.php
  database/migrations/2024_05_21_135734_update_planilla_general_function.php
Labels: enhancement

#1880 Se añadió drop_function y formato a la migración update_planilla_general
  database/migrations/2024_05_21_135734_update_planilla_general_function.php
Labels: change

#1891 Añadido validaciones al editar renta Senasir
  app/Http/Controllers/EconomicComplementController.php
  resources/assets/js/components/eco_com/Qualification.vue
Labels: bug

#1883 Registro de descuentos en la tabla movimientos de pagos en demasía
  app/Http/Controllers/EconomicComplementController.php
  app/Models/EconomicComplement/EcoComMovement.php
Labels: enhancement

#1896 Se arregló para que importaciones APS no editen rentas manuales
  app/Http/Controllers/EcoComImportExportController.php
Labels: bug

#1897 Agregando validación de monto a pagar mayor al balance
  app/Http/Controllers/EconomicComplementController.php
Labels: enhancement
