Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2025-03, with the labels that each got.

#2087 bug mismo nombre
  resources/assets/js/components/ret_fun/Qualification.vue
  resources/views/ret_fun/qualification.blade.php
Labels: bug

#2095 PROCEDIMIENTO PARA PARENTESCO DEL LOS BENEFICIARIOS CUANDO SEAN MENORES DE EDAD (TUTOR)
  app/Http/Controllers/QuotaAidCertificationController.php
  app/Http/Controllers/QuotaAidMortuaryController.php
  app/Http/Controllers/RetirementFundController.php
  app/Models/KinshipBeneficiary.php
  app/Models/QuotaAidMortuary/QuotaAidAdvisor.php
  app/Models/RetirementFund/RetFunAdvisor.php
  app/Models/RetirementFund/RetirementFund.php
  database/migrations/2025_02_28_120915_create_table_kinship_beneficiary.php
  resources/assets/js/components/quota_aid/Beneficiary.vue
  resources/assets/js/components/quota_aid/ShowBeneficiaries.vue
  resources/assets/js/components/quota_aid/Step3Beneficiaries.vue
  resources/assets/js/components/ret_fun/Beneficiary.vue
  resources/assets/js/components/ret_fun/BeneficiaryList.vue
  resources/assets/js/components/ret_fun/ShowBeneficiaries.vue
  resources/views/affiliates/show.blade.php
  resources/views/quota_aid/beneficiaries_list.blade.php
  resources/views/quota_aid/print/liquidation.blade.php
  resources/views/quota_aid/show.blade.php
  resources/views/ret_fun/beneficiaries_list.blade.php
  resources/views/ret_fun/create.blade.php
  resources/views/ret_fun/print/liquidation.blade.php
  resources/views/ret_fun/show.blade.php
  resources/views/ret_fun/step3_beneficiaries.blade.php
Labels: enhancement, New

#2096 Ajustes en la calificación de FR
  app/Http/Controllers/AffiliateController.php
  app/Http/Controllers/ContributionController.php
  app/Http/Controllers/RetirementFundController.php
  app/Models/Affiliate.php
  app/Models/RetirementFund/RetirementFund.php
  resources/assets/js/components/ret_fun/Qualification.vue
  resources/assets/js/components/ret_fun/Step2Applicant.vue
  resources/views/contribution/affiliate_contribution_show.blade.php
  resources/views/ret_fun/create.blade.php
  resources/views/ret_fun/qualification.blade.php
  resources/views/ret_fun/step2_applicant.blade.php
Labels: change

#2103 Quitar correlativo por duplicidad de todas las certificaciones de fon…
  app/Http/Controllers/RetirementFundCertificationController.php
Labels: enhancement
