Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2025-04, with the labels that each got.

#2115 Se añadieron variables a la clase ID
  app/Helpers/ID.php
  app/Http/Controllers/RetirementFundCertificationController.php
  resources/views/ret_fun/show.blade.php
Labels: enhancement, change

#2110 Records de cónyuge
  app/Http/Controllers/SpouseController.php
  app/Models/Spouse.php
  app/Observers/SpouseObserver.php
  app/Providers/AppServiceProvider.php
  resources/assets/js/components/affiliate/Record.vue
  routes/web.php
Labels: enhancement

#2116 bug mostrar duplicación de dirección
  resources/views/ret_fun/print/liquidation.blade.php
Labels: bug
