Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2025-05, with the labels that each got.

#2119 Adición de autorización para enviar notificaciones al afiliado
  resources/views/eco_com/print/reception.blade.php
Labels: enhancement

#2126 Corrección en la sumatoria de aportes
  app/Models/Affiliate.php
Labels: bug

#2129 Se añadió columna fecha liquidación a FR
  app/Http/Controllers/RetirementFundController.php
  resources/views/ret_fun/index.blade.php
Labels: change

#2132 ACTUALIZACIÓN PARA MOSTRAR NOMBRE COMPLETO DEL TUTOR
  resources/views/ret_fun/print/liquidation.blade.php
Labels: bug

#2133 ACTUALIZACIÓN PARA MOSTRAR SUBTITULO LA SUBMODALIDAD
  app/Http/Controllers/QuotaAidCertificationController.php
Labels: bug

#2138 Limpieza de documentos en afiliado regular de CE
  resources/assets/js/components/eco_com/Step1Requirements.vue
Labels: bug

#2140 SE AUMENTO COLUMNA NUMERO DE PRESTAMO PARA DESCUENTOS DE TYPO GARANTES Y PRESTAMO EN FORM LIQUIDACION
  resources/views/ret_fun/print/liquidation.blade.php
Labels: bug

#2141 Validacion de palabra para modalidad de fondo de retiro - fallecimiento (form. liquidación) y separador de miles
  resources/views/ret_fun/print/liquidation.blade.php
Labels: bug

#2143 Eliminación de correlativo por área en FRCAM
  app/Http/Controllers/QuotaAidCertificationController.php
  app/Http/Controllers/QuotaAidMortuaryController.php
  app/Http/Controllers/RetirementFundCertificationController.php
  app/Http/Controllers/RetirementFundController.php
  resources/assets/js/components/utils/SweetAlertModal.vue
  resources/views/print_global/send.blade.php
  resources/views/quota_aid/index.blade.php
  resources/views/quota_aid/print/headship_review.blade.php
  resources/views/quota_aid/show.blade.php
  resources/views/ret_fun/index.blade.php
  resources/views/ret_fun/print/headship_review.blade.php
  resources/views/ret_fun/show.blade.php
  routes/web.php
Labels: change

#2146 Corrección en devolución de trámites de QAM
  app/Http/Controllers/InboxController.php
Labels: bug

#2148 Cambio en la verificación de hash del kiosko
  app/Http/Middleware/VerifyBearerToken.php
Labels: change
