Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2025-06, with the labels that each got.

#2154 Intercambio de letra "y" por "/"
  resources/views/quota_aid/print/liquidation.blade.php
  resources/views/ret_fun/print/liquidation.blade.php
Labels: enhancement

#2156 Eliminacion de validacion doble dispositivo
  app/Http/Controllers/API/AuthController.php
Labels: change

#2166 Funcionalidad para devolver datos de la cónyuge o afiliado ya registrado
  app/Http/Controllers/SpouseController.php
  resources/assets/js/components/spouse/ShowSpouse.vue
  resources/views/spouses/spouse_personal_information.blade.php
  routes/web.php
Labels: enhancement

#2170 Correción de comentarios
  resources/views/ret_fun/print/liquidation.blade.php
Labels: bug

#2178 Guardado de información de la conyuge
  app/Http/Controllers/SpouseController.php
  resources/assets/js/components/spouse/ShowSpouse.vue
Labels: enhancement

#2180 Limpieza de codigo y solucion de bug
  app/Http/Controllers/AffiliateController.php
  resources/views/eco_com/step1_requirements.blade.php
  resources/views/quota_aid/step1_requirements.blade.php
  resources/views/ret_fun/step1_requirements.blade.php
Labels: bug, change
