Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2025-02, with the labels that each got.

#2068 Ajuste de id - Retención judicial Cuota Auxilio controller
  app/Http/Controllers/QuotaAidMortuaryController.php
Labels: change

#2074 Pie de firmas Certificación de Calificación QAM y FR
  app/Http/Controllers/QuotaAidCertificationController.php
  app/Http/Controllers/RetirementFundCertificationController.php
  resources/views/quota_aid/print/beneficiaries_qualification.blade.php
  resources/views/quota_aid/print/qualification_data.blade.php
  resources/views/ret_fun/print/beneficiaries_qualification.blade.php
  resources/views/ret_fun/print/qualification_average_salary_quotable.blade.php
  resources/views/ret_fun/print/qualification_data_availability.blade.php
  resources/views/ret_fun/print/qualification_step_data.blade.php
  resources/views/ret_fun/print/signature_footer_2.blade.php
Labels: change

#2075 CAMBIOS PARA FONDO DE RETIRO REGLAMENTO 2024 RETENCIONES Y PROMEDIO LIMITADO
  app/Http/Controllers/QuotaAidMortuaryController.php
  app/Http/Controllers/RetirementFundCertificationController.php
  app/Http/Controllers/RetirementFundController.php
  database/migrations/2025_02_14_102613_add_column_limit_average.php
  database/migrations/2025_02_20_145026_add_columns_reinstate_affiliate.php
  database/seeds/DataBackupAverageQuotable.php
  database/seeds/UpdateRetirementFundRegulations2024.php
  resources/assets/js/components/quota_aid/Info.vue
  resources/assets/js/components/quota_aid/JudicialRetention.vue
  resources/assets/js/components/quota_aid/Qualification.vue
  resources/assets/js/components/ret_fun/Info.vue
  resources/assets/js/components/ret_fun/JudicialRetention.vue
  resources/assets/js/components/ret_fun/Qualification.vue
  resources/views/affiliates/print/full_personal_info.blade.php
  resources/views/print_global/print.blade.php
  resources/views/quota_aid/info.blade.php
  resources/views/quota_aid/qualification.blade.php
  resources/views/ret_fun/info.blade.php
  resources/views/ret_fun/print/applicant.blade.php
  resources/views/ret_fun/print/liquidation.blade.php
  resources/views/ret_fun/print/qualification_step_data.blade.php
  resources/views/ret_fun/qualification.blade.php
  resources/views/ret_fun/show.blade.php
  resources/views/ret_fun/summary_qualification.blade.php
  routes/web.php
Labels: enhancement, New

#2078 Cambio en los requisitos de complemento
  app/Models/ProcedureDocument.php
  database/seeds/AddNewDocumentsCE21022025Seeder.php
Labels: change, data base
