Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/PVT-BE, pull requests merged in 2025-01, with the labels that each got.

#2041 Añadido viuda a la verificación de complemento
  app/Http/Controllers/API/EconomicComplementController.php
Labels: bug

#2043 Se aumento verificar viuda y se añadió validaciones
  app/Http/Controllers/API/EconomicComplementController.php
Labels: bug, enhancement

#2044 Se aumento verificar viuda y se añadió validaciones
  app/Http/Controllers/API/EconomicComplementController.php
Labels: bug, enhancement

#2062 frontend basico para importación de documentos de afiliados, consumir rutas de los microservicios
  app/Gateway/AffiliateController.php
  resources/views/gateway/analysis_documents_affiliate.blade.php
  resources/views/gateway/auth.blade.php
  resources/views/gateway/error.blade.php
  resources/views/gateway/import_documents_affiliate.blade.php
  resources/views/gateway/plantilla.blade.php
  routes/gateway.php
Labels: New

#2064 arreglo bug de condicion
  resources/views/gateway/analysis_documents_affiliate.blade.php
Labels: bug

#2065 arreglo bug de condicion merge requisitos
  resources/views/gateway/analysis_documents_affiliate.blade.php
Labels: bug
